### ISSUE TITLE
Update timelines for fixing the battery issue @ Ami

### ISSUE THREAD

**Issue by shankardevy** [Auroville/lpwan#3]
Tency and Giulio needs to be updated on the timelines for battery issue we are facing at Ami.

**Comment by shankardevy** [comment]
I replied to Tency and Giulio. I didn't hear from you on the email so I have sent it as it's to avoid delay. I hope that's ok. Please do read the email and let me know if there is anything that needs to be corrected or added which can be sent as a follow up email.

**Comment by azhaganandhan** [comment]
Looks good, I will check all other devices and let you know the status by friday.
