### ISSUE TITLE
Provide an update on MCCI catena and water sensor device status

### ISSUE THREAD

**Issue by shankardevy** [Auroville/lpwan#4]
Test all catena boards, batteries and the water sensor and provide a report to Tency and Guilio.

**Comment by azhaganandhan** [comment]
Totally Boards =  7 board(including one present in ami)
working boards = 5
Not working board = 2
Batteries  = 7(3bulged but working)
Another one is in working condition which is present in the ami well

**Comment by shankardevy** [comment]
Water sensors? Can we have a report on that as well? Ideally with a PVC pipe to test it as we did previously?

**Comment by shankardevy** [comment]
This task is originally planned * 28 days ago*. We still have it *in progress*
